### ISSUE TITLE
Blank white background upon selecting of directories or files

### ISSUE THREAD

**Issue by GreenLunar** [ClassicOS-Themes/ClassicOS-2000-Theme#2]
ClassicOS98
![image](https://user-images.githubusercontent.com/2053884/202369603-513e9f35-eb92-4998-92ba-2693a24bbd07.png)

Chicago95 https://github.com/grassmunk/Chicago95
![image](https://user-images.githubusercontent.com/2053884/202369651-154153ea-e3da-45f6-9c34-17c66696b846.png)

Redmond97 https://www.pling.com/p/1313764/
![image](https://user-images.githubusercontent.com/2053884/202369725-25504384-c3fb-45de-a146-b0d82756252a.png)

**Comment by ClassicOS-Themes** [comment]
Well, I really should get around to fixing that one of these days...

When I do though, would it be preferable to use the blue translucent selection rectangle like in the other screenshots, or should I go for the more authentic [dotted outline selection rectangle](https://i.stack.imgur.com/KB3EM.png)?

**Comment by GreenLunar** [comment]
On Mon, 21 Nov 2022 13:44:07 -0800
ClassicOS-Themes ***@***.***> wrote:

> Well, I really should get around to fixing that one of these days...
>
> When I do though, would it be preferable to use the blue translucent
> selection rectangle like in the other screenshots, or should I go for
> the more authentic [dotted outline selection
> rectangle](https://i.stack.imgur.com/KB3EM.png)?
>

Let's try the dotted and see how it transpires.

**Comment by ClassicOS-Themes** [comment]
Ok, so I've implemented the dotted selection outline. It seems to work well in Thunar, but Nemo and Caja were rendering a solid line instead of a dotted line, so for those applications, the translucent "modern" selection rectangle is used instead.


Let me know what you think

**Comment by GreenLunar** [comment]
Good choice! Beautiful!

Tested with:
ClassicOS98
ClassicOS98-Underwater
ClassicOS2000-Standard
ClassicOS2000-High-Contrast-1
ClassicOS2000-Plum
ClassicOS98-Cartoon-Society
ClassicOS2000-Plumpkin

Tested on:
LXQt with Xfwm4 (X11)

**Comment by GreenLunar** [comment]
Did you notice that GTK+ behaves (and maybe also looks) differently under Sway (Wayland)?
I've no animations nor fading effects, which is great, but the point is that GTK+ looks behaves differently.
